spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/notebook
      driver-class-name: org.h2.Driver
      username: sa
      password: